-- Unifying codes
UPDATE public.accounts SET code = '4100' WHERE product = 'hotel' AND name = 'Room Revenue';
UPDATE public.accounts SET code = '4101' WHERE product = 'hotel' AND name = 'Early Check-in / Late Check-out Revenue';
UPDATE public.accounts SET code = '4102' WHERE product = 'hotel' AND name = 'Beverage Revenue';
UPDATE public.accounts SET code = '4103' WHERE product = 'hotel' AND name = 'F&B Revenue';
UPDATE public.accounts SET code = '5100' WHERE product = 'hotel' AND name = 'PMS Cost';
UPDATE public.accounts SET code = '5101' WHERE product = 'hotel' AND name = 'Travel Agent / OTA Commissions';
UPDATE public.accounts SET code = '5102' WHERE product = 'hotel' AND name = 'Stationery & Printing';
UPDATE public.accounts SET code = '5103' WHERE product = 'hotel' AND name = 'F&B Service Labor';
UPDATE public.accounts SET code = '5104' WHERE product = 'hotel' AND name = 'Food Cost';
UPDATE public.accounts SET code = '5105' WHERE product = 'hotel' AND name = 'Software & Licensing';
UPDATE public.accounts SET code = '5106' WHERE product = 'hotel' AND name = 'Accounting & Audit Fees';
UPDATE public.accounts SET code = '5011' WHERE product = 'hotel' AND name = 'Bank Charges';
UPDATE public.accounts SET code = '5107' WHERE product = 'hotel' AND name = 'Office Supplies';
UPDATE public.accounts SET code = '5040' WHERE product = 'hotel' AND name = 'Legal & Professional Fees';
UPDATE public.accounts SET code = '5108' WHERE product = 'hotel' AND name = 'Purchase Department Overhead';
UPDATE public.accounts SET code = '5109' WHERE product = 'hotel' AND name = 'Inventory Shrinkage / Wastage';
UPDATE public.accounts SET code = '5110' WHERE product = 'hotel' AND name = 'Digital Marketing';
UPDATE public.accounts SET code = '5111' WHERE product = 'hotel' AND name = 'Print & Offline Marketing';
UPDATE public.accounts SET code = '5112' WHERE product = 'hotel' AND name = 'Loyalty Program Costs';
UPDATE public.accounts SET code = '5113' WHERE product = 'hotel' AND name = 'Electricity';
UPDATE public.accounts SET code = '5114' WHERE product = 'hotel' AND name = 'Water';
UPDATE public.accounts SET code = '5115' WHERE product = 'hotel' AND name = 'Repairs & Maintenance';
UPDATE public.accounts SET code = '5116' WHERE product = 'hotel' AND name = 'Housekeeping Supplies';
UPDATE public.accounts SET code = '1100' WHERE product = 'restaurant' AND name = 'Kitchen Equipment';
UPDATE public.accounts SET code = '4104' WHERE product = 'restaurant' AND name = 'Food Sales';
UPDATE public.accounts SET code = '4105' WHERE product = 'restaurant' AND name = 'Beverage Sales';
UPDATE public.accounts SET code = '5104' WHERE product = 'restaurant' AND name = 'Food Cost';
UPDATE public.accounts SET code = '5034' WHERE product = 'restaurant' AND name = 'Beverage Cost';
UPDATE public.accounts SET code = '5117' WHERE product = 'restaurant' AND name = 'Management Labor';
UPDATE public.accounts SET code = '5118' WHERE product = 'restaurant' AND name = 'Staff Labor';
UPDATE public.accounts SET code = '5119' WHERE product = 'restaurant' AND name = 'Direct Operating Expenses';
UPDATE public.accounts SET code = '5120' WHERE product = 'restaurant' AND name = 'Music & Entertainment';
UPDATE public.accounts SET code = '5121' WHERE product = 'restaurant' AND name = 'Marketing';
UPDATE public.accounts SET code = '5122' WHERE product = 'restaurant' AND name = 'Utilities';
UPDATE public.accounts SET code = '5123' WHERE product = 'restaurant' AND name = 'General & Administrative';
UPDATE public.accounts SET code = '5115' WHERE product = 'restaurant' AND name = 'Repairs & Maintenance';
UPDATE public.accounts SET code = '5203' WHERE product = 'restaurant' AND name = 'Rent / Lease Payment';
UPDATE public.accounts SET code = '5124' WHERE product = 'restaurant' AND name = 'Property Insurance';
UPDATE public.accounts SET code = '5125' WHERE product = 'restaurant' AND name = 'Property Taxes';
UPDATE public.accounts SET code = '5126' WHERE product = 'restaurant' AND name = 'License & Government Fees';
UPDATE public.accounts SET code = '5127' WHERE product = 'restaurant' AND name = 'AMC (Annual Maintenance Contracts)';
UPDATE public.accounts SET code = '5206' WHERE product = 'restaurant' AND name = 'Depreciation & Amortization';
UPDATE public.accounts SET code = '5207' WHERE product = 'restaurant' AND name = 'Loan Interest';
